steps:
  - name: Increase PHP CLI memory limit
    plugin: Shell
    command: echo "memory_limit = 512M" > /etc/php5/cli/conf.d/ding2.ini
  - name: Increase PHP Apache memory limit
    plugin: Shell
    command: echo "memory_limit = 512M" > /etc/php5/apache2/conf.d/ding2.ini
  - name: Check PHP memory limit
    plugin: Shell
    command: php -i
  - name: Build site
    plugin: Drupal
    makeFile: drupal.make
    runInstall: true
    profileName: ding2
    installArgs: >
      --site-name="DDBCMS"
      --account-pass=ddbcms
  - name: Configure site
    plugin: Shell
    command: >
      drush pm-enable ding_example_content -y;
  - name: Setup file permission
    plugin: Shell
    command: >
      chgrp -Rv www-data sites/default/files;
      chmod -v 2775 /var/www/html/sites/default/files;
